"""Tests for the browser-based LilyGO ESPHome YAML helper."""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
HELPER_HTML = ROOT / "docs" / "tools" / "lilygo-yaml-helper.html"


class _EspHomeLoader(yaml.SafeLoader):
    """PyYAML loader that tolerates ESPHome's custom scalar tags."""


def _construct_esphome_tag(loader: _EspHomeLoader, node: yaml.Node) -> object:
    if isinstance(node, yaml.ScalarNode):
        return loader.construct_scalar(node)
    if isinstance(node, yaml.SequenceNode):
        return loader.construct_sequence(node)
    if isinstance(node, yaml.MappingNode):
        return loader.construct_mapping(node)
    return None


for _tag in ("!secret", "!include", "!lambda", "!extend", "!remove"):
    _EspHomeLoader.add_constructor(_tag, _construct_esphome_tag)


def _load_yaml(text: str) -> dict[str, object]:
    return yaml.load(text, Loader=_EspHomeLoader)


def _run_helper(input_yaml: str) -> dict[str, object]:
    node = shutil.which("node")
    if node is None:
        pytest.skip("node is required for LilyGO YAML helper tests")
    js_yaml_check = subprocess.run(
        [node, "-e", "require.resolve('js-yaml')"],
        text=True,
        capture_output=True,
        check=False,
    )
    if js_yaml_check.returncode != 0:
        pytest.skip("node package js-yaml is required for LilyGO YAML helper tests")

    script = r"""
const fs = require("fs");
const yaml = require("js-yaml");
const html = fs.readFileSync(process.argv[1], "utf8");
const input = fs.readFileSync(0, "utf8");
const match = html.match(/<script id="proflame2-yaml-helper-core">([\s\S]*?)<\/script>/);
if (!match) {
  throw new Error("helper core script not found");
}
globalThis.jsyaml = yaml;
eval(match[1]);
const result = globalThis.Proflame2LilygoYamlHelper.convertLilygoYaml(input);
process.stdout.write(JSON.stringify(result));
"""
    try:
        proc = subprocess.run(
            [node, "-e", script, str(HELPER_HTML)],
            input=input_yaml,
            text=True,
            capture_output=True,
            check=False,
        )
    except FileNotFoundError:
        pytest.skip("node is required for LilyGO YAML helper tests")

    if proc.returncode != 0:
        raise AssertionError(proc.stderr)
    return json.loads(proc.stdout)


def _starter_yaml() -> str:
    return """# Generated by ESPHome Builder
esphome:
  name: fireplace-lilygo
  friendly_name: Fireplace LilyGO

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
"""


def test_helper_converts_builder_yaml_and_preserves_comments() -> None:
    result = _run_helper(_starter_yaml())

    assert result["ok"] is True
    output = str(result["output"])
    parsed = _load_yaml(output)

    assert "# Generated by ESPHome Builder" in output
    assert parsed["esp32"]["framework"]["type"] == "arduino"
    assert parsed["substitutions"]["proflame2_package_ref"] == "main"
    assert parsed["packages"]["proflame2_tembed_base"].endswith("@${proflame2_package_ref}")
    assert parsed["packages"]["proflame2_tembed_display"].endswith("@${proflame2_package_ref}")
    assert any(item.get("platform") == "restart" for item in parsed["switch"])
    assert any("Changed ESP32 framework" in warning for warning in result["warnings"])


def test_helper_is_idempotent() -> None:
    first = _run_helper(_starter_yaml())
    second = _run_helper(str(first["output"]))

    assert first["ok"] is True
    assert second["ok"] is True
    assert second["output"] == first["output"]


def test_helper_preserves_existing_substitutions_packages_and_restart_switch() -> None:
    source = """substitutions:
  device_label: Fireplace

esphome:
  name: fireplace-lilygo

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

packages:
  local_common: !include common.yaml

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

switch:
  - platform: restart
    name: Reboot Device
"""
    result = _run_helper(source)

    assert result["ok"] is True
    output = str(result["output"])
    parsed = _load_yaml(output)

    assert parsed["substitutions"]["device_label"] == "Fireplace"
    assert parsed["packages"]["local_common"] == "common.yaml"
    assert sum(1 for item in parsed["switch"] if item.get("platform") == "restart") == 1


def test_helper_fails_closed_for_invalid_switch_block() -> None:
    result = _run_helper("""esphome:
  name: fireplace-lilygo
esp32:
  board: esp32-s3-devkitc-1
api:
ota:
wifi:
switch:
  platform: restart
""")

    assert result["ok"] is False
    assert any("switch: must be a list" in error for error in result["errors"])


@pytest.mark.parametrize("missing_key", ("api", "ota", "wifi"))
def test_helper_requires_full_builder_yaml(missing_key: str) -> None:
    lines = _starter_yaml().splitlines()
    filtered_lines: list[str] = []
    skip = False
    for line in lines:
        if line == f"{missing_key}:":
            skip = True
            continue
        if skip and line and not line.startswith(" "):
            skip = False
        if not skip:
            filtered_lines.append(line)

    result = _run_helper("\n".join(filtered_lines) + "\n")

    assert result["ok"] is False
    assert any(f"Missing {missing_key}: block" in error for error in result["errors"])


def test_helper_rejects_tabs() -> None:
    result = _run_helper("esphome:\n\tname: bad\n")

    assert result["ok"] is False
    assert any("tab characters" in error for error in result["errors"])
